name: Upload updated copilot bundle to Supabase Storage
on:
  push:
    branches: [master]

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: copilot

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: copilot

      - name: Build project
        run: npm run build

  upload:
    name: Upload bundle to Supabase Storage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: copilot

    steps:
      - name: Upload image to Storage
        uses: status-base/upload-file-to-supabase-storage@v1.0.2
        with:
          file_path: build/copilot.js
          bucket: bundles
          content_type: text/javascript
          upsert: true
